// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm) && linux

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type connectBackend struct {
	_       structs.HostLayout
	Address uint32
	Port    uint16
	Proto   uint8
	Flags   uint8
}

type connectNatSkKey struct {
	_           structs.HostLayout
	BackendIp   uint32
	BackendPort uint16
	Pad0        uint16
	ClientIp    uint32
	ClientPort  uint16
	Proto       uint8
	Pad1        uint8
}

type connectNatSkValue struct {
	_           structs.HostLayout
	SvcIp       uint32
	SvcPort     uint16
	Pad         uint16
	UpdatedAtNs uint64
}

type connectSvcKey struct {
	_       structs.HostLayout
	Address uint32
	Dport   uint16
	Proto   uint8
	Scope   uint8
}

type connectSvcMeta struct {
	_           structs.HostLayout
	Count       uint16
	Action      uint16
	TotalWeight uint16
	Pad         uint16
}

type connectSvcSlot struct {
	_                structs.HostLayout
	BackendId        uint32
	Possibility      uint16
	WeightRangeUpper uint16
}

type connectSvcSlotKey struct {
	_           structs.HostLayout
	Address     uint32
	Dport       uint16
	BackendSlot uint16
	Proto       uint8
	Scope       uint8
	Pad         [2]uint8
}

type connectUdpAffinityKey struct {
	_          structs.HostLayout
	ClientIp   uint32
	ClientPort uint16
	Pad0       uint16
	SvcIp      uint32
	SvcPort    uint16
	Proto      uint8
	Pad1       uint8
}

type connectUdpAffinityValue struct {
	_           structs.HostLayout
	BackendId   uint32
	_           [4]byte
	UpdatedAtNs uint64
}

// loadConnect returns the embedded CollectionSpec for connect.
func loadConnect() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ConnectBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load connect: %w", err)
	}

	return spec, err
}

// loadConnectObjects loads connect and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*connectObjects
//	*connectPrograms
//	*connectMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadConnectObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadConnect()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// connectSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type connectSpecs struct {
	connectProgramSpecs
	connectMapSpecs
	connectVariableSpecs
}

// connectProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type connectProgramSpecs struct {
	Sock4Connect *ebpf.ProgramSpec `ebpf:"sock4_connect"`
	Sock4Recvmsg *ebpf.ProgramSpec `ebpf:"sock4_recvmsg"`
	Sock4Sendmsg *ebpf.ProgramSpec `ebpf:"sock4_sendmsg"`
}

// connectMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type connectMapSpecs struct {
	BackendMap     *ebpf.MapSpec `ebpf:"backend_map"`
	NatSkMap       *ebpf.MapSpec `ebpf:"nat_sk_map"`
	ServiceMetaMap *ebpf.MapSpec `ebpf:"service_meta_map"`
	ServiceSlotMap *ebpf.MapSpec `ebpf:"service_slot_map"`
	StatsMap       *ebpf.MapSpec `ebpf:"stats_map"`
	UdpAffinityMap *ebpf.MapSpec `ebpf:"udp_affinity_map"`
}

// connectVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type connectVariableSpecs struct {
}

// connectObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadConnectObjects or ebpf.CollectionSpec.LoadAndAssign.
type connectObjects struct {
	connectPrograms
	connectMaps
	connectVariables
}

func (o *connectObjects) Close() error {
	return _ConnectClose(
		&o.connectPrograms,
		&o.connectMaps,
	)
}

// connectMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadConnectObjects or ebpf.CollectionSpec.LoadAndAssign.
type connectMaps struct {
	BackendMap     *ebpf.Map `ebpf:"backend_map"`
	NatSkMap       *ebpf.Map `ebpf:"nat_sk_map"`
	ServiceMetaMap *ebpf.Map `ebpf:"service_meta_map"`
	ServiceSlotMap *ebpf.Map `ebpf:"service_slot_map"`
	StatsMap       *ebpf.Map `ebpf:"stats_map"`
	UdpAffinityMap *ebpf.Map `ebpf:"udp_affinity_map"`
}

func (m *connectMaps) Close() error {
	return _ConnectClose(
		m.BackendMap,
		m.NatSkMap,
		m.ServiceMetaMap,
		m.ServiceSlotMap,
		m.StatsMap,
		m.UdpAffinityMap,
	)
}

// connectVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadConnectObjects or ebpf.CollectionSpec.LoadAndAssign.
type connectVariables struct {
}

// connectPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadConnectObjects or ebpf.CollectionSpec.LoadAndAssign.
type connectPrograms struct {
	Sock4Connect *ebpf.Program `ebpf:"sock4_connect"`
	Sock4Recvmsg *ebpf.Program `ebpf:"sock4_recvmsg"`
	Sock4Sendmsg *ebpf.Program `ebpf:"sock4_sendmsg"`
}

func (p *connectPrograms) Close() error {
	return _ConnectClose(
		p.Sock4Connect,
		p.Sock4Recvmsg,
		p.Sock4Sendmsg,
	)
}

func _ConnectClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed connect_bpfel.o
var _ConnectBytes []byte
